import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Headers/page'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Hassan Omar Mohamed</title>
        <meta property="Auther" content="Hassan Omar Mohamed" />
      </Head>
      <body className={inter.className}>
    <Header/>

        {children}</body>
    </html>
  )
}
